# common clock types
# obj-$(CONFIG_HAVE_CLK)		+= clk-devres.o
# obj-$(CONFIG_CLKDEV_LOOKUP)	+= clkdev.o
# obj-$(CONFIG_OF)	        += clk.o
# obj-$(CONFIG_COMMON_CLK)	+= clk-divider.o
# obj-$(CONFIG_COMMON_CLK)	+= clk-fixed-factor.o
# obj-$(CONFIG_COMMON_CLK)	+= clk-fixed-rate.o
# obj-$(CONFIG_COMMON_CLK)	+= clk-gate.o
# obj-$(CONFIG_COMMON_CLK)	+= clk-multiplier.o
# obj-$(CONFIG_COMMON_CLK)	+= clk-mux.o
# obj-$(CONFIG_COMMON_CLK)	+= clk-composite.o
# obj-$(CONFIG_COMMON_CLK)	+= clk-fractional-divider.o
# obj-$(CONFIG_COMMON_CLK)	+= clk-gpio.o
# ifeq ($(CONFIG_OF), y)
# obj-$(CONFIG_COMMON_CLK)	+= clk-conf.o
# endif

# hardware specific clock types
# ...（全部注释掉，除非你需要某些特定平台的主线 clk 驱动）...

# 只保留 msm 相关
obj-y					+= msm/
